server:
  port: 8082

spring:
  config:
    name: big-market-rule-engine-app
  profiles:
    active: dev

ice:
  app: 2
  #  server: zookeeper:localhost:2181,localhost:2182,localhost:2183
  server: localhost:18121
  scan: com.kk.domain.rule.model
  pool:
    parallelism: -1
test:
  value: 123
environment: dev